import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Navbar from "../components/Navbar";
import { useCart } from "../CartContext";
function Checkout(){
 const {cart,cartTotal,clearCart}=useCart(); const nav=useNavigate(); const [user,setUser]=useState(null); const [form,setForm]=useState({name:"",email:"",phone:"",address:"",city:"",state:"Maharashtra",pincode:""}); const [paymentMethod,setPayment]=useState("Cash on Delivery"); const [errors,setErrors]=useState({}); const [loading,setLoading]=useState(false);
 useEffect(()=>{fetch('/api/auth?action=me').then(r=>r.json()).then(d=>{if(d.user){setUser(d.user);setForm(f=>({...f,name:d.user.name||f.name,email:d.user.email||f.email,phone:d.user.mobile||f.phone}))}}).catch(()=>{})},[]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 const submit=async e=>{e.preventDefault();let x={}; if(!user)x.auth="Please login before placing an order."; if(!form.name)x.name="Required"; if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(form.email))x.email="Valid email required";if(!/^\d{10}$/.test(form.phone))x.phone="10 digit mobile required";if(!form.address)x.address="Required";if(!form.city)x.city="Required";if(!/^\d{6}$/.test(form.pincode))x.pincode="6 digit PIN required";if(Object.keys(x).length){setErrors(x);return}setLoading(true);try{const orderId=`CFX${Date.now().toString().slice(-8)}`;const payload={orderId,customer:form,items:cart,total:cartTotal,paymentMethod};const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not place order');localStorage.setItem('latestOrderId',orderId);localStorage.setItem('latestOrder',JSON.stringify({...payload,id:orderId,date:new Date().toLocaleString('en-IN'),status:'Confirmed'}));clearCart();nav('/order-success')}catch(err){setErrors({api:err.message})}finally{setLoading(false)}};
 if(!cart.length)return <><Navbar/><main className="checkout-page empty-checkout"><p className="eyebrow">CYBERFLIX SYSTEMS LLP</p><h1>YOUR CART IS EMPTY</h1><Link to="/products" className="checkout-btn">SHOP COMPONENTS →</Link></main></>;
 return <><Navbar/><main className="checkout-page"><section className="checkout-header"><p className="eyebrow">CYBERFLIX SYSTEMS LLP</p><h1>CHECKOUT</h1><p>Secure checkout for your Cyberflix order.</p></section>{!user&&<div className="checkout-form-card"><strong>Login required to place an order.</strong> <Link to="/login">Login / Create account →</Link></div>}{errors.auth&&<small className="form-error">{errors.auth}</small>}<section className="checkout-layout"><div className="checkout-form-card"><p className="eyebrow">DELIVERY DETAILS</p><form onSubmit={submit}>{[['name','Full Name'],['email','Email'],['phone','Phone Number'],['address','Delivery Address'],['city','City'],['state','State'],['pincode','PIN Code']].map(([n,l])=><div className="checkout-field" key={n}><label>{l}</label>{n==='address'?<textarea name={n} rows="4" value={form[n]} onChange={change}/>:<input name={n} value={form[n]} maxLength={n==='phone'?10:n==='pincode'?6:undefined} onChange={change}/>} {errors[n]&&<small className="form-error">{errors[n]}</small>}</div>)}<div className="checkout-field"><label>Payment Method</label><select value={paymentMethod} onChange={e=>setPayment(e.target.value)}><option>Cash on Delivery</option><option>UPI</option><option>Card</option></select></div>{errors.api&&<small className="form-error">{errors.api}</small>}<button className="place-order-btn" disabled={loading||!user}>{loading?'PLACING ORDER...':`PLACE ORDER • ₹${cartTotal.toLocaleString('en-IN')}`}</button></form></div><aside className="checkout-summary"><p className="eyebrow">ORDER SUMMARY</p>{cart.map(i=><div className="summary-item" key={i.id}><span>{i.name} × {i.quantity}</span><strong>₹{(i.price*i.quantity).toLocaleString('en-IN')}</strong></div>)}<hr/><div className="summary-total"><span>TOTAL</span><strong>₹{cartTotal.toLocaleString('en-IN')}</strong></div></aside></section></main></>}
export default Checkout;
