import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";

function Login(){
 const navigate=useNavigate(); const [register,setRegister]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
 const [form,setForm]=useState({name:"",email:"",mobile:"",password:""});
 const submit=async e=>{e.preventDefault();setError("");if(form.password.length<6)return setError("Password must be at least 6 characters.");setLoading(true);try{const r=await fetch(`/api/auth?action=${register?'register':'login'}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)throw Error(d.error||"Request failed");localStorage.setItem("cyberflixUser",JSON.stringify(d.user));navigate("/");}catch(err){setError(err.message)}finally{setLoading(false)}};
 return <><main className="login-page"><section className="login-card"><p className="eyebrow">CYBERFLIX SYSTEMS LLP</p><h1>{register?"CREATE ACCOUNT":"WELCOME BACK"}</h1><p>{register?"Create your Cyberflix account to track orders and save builds.":"Login to access your orders, wishlist and saved builds."}</p><form onSubmit={submit}>{register&&<div className="login-field"><label>Name</label><input name="name" required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full name"/></div>}<div className="login-field"><label>Email</label><input type="email" name="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="you@example.com"/></div>{register&&<div className="login-field"><label>Mobile</label><input name="mobile" maxLength="10" value={form.mobile} onChange={e=>setForm({...form,mobile:e.target.value.replace(/\D/g,"")})} placeholder="10 digit mobile"/></div>}<div className="login-field"><label>Password</label><input type="password" name="password" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Minimum 6 characters"/></div>{error&&<small className="form-error">{error}</small>}<button className="login-submit-btn" disabled={loading}>{loading?"PLEASE WAIT...":register?"CREATE ACCOUNT →":"LOGIN →"}</button></form><button className="login-back-link" onClick={()=>{setRegister(!register);setError("")}}>{register?"Already have an account? Login":"New to Cyberflix? Create account"}</button><Link to="/products" className="login-back-link">← Continue Shopping</Link></section></main></>
}
export default Login;
